version: 2
updates:

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
    # Prevent updates to urllib3 >= v1.26.16 which can trigger deadlocks in
    # gevent. See notes in requirements/requirements.in.
    - dependency-name: "urllib3"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
    # Only send PRs for patch versions of Python.
    - dependency-name: "python"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
