version: '3'
services:
  nginx-proxy:
    image: nginx:1.17.6-alpine
    ports:
      - '127.0.0.1:9085:9085'
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/viahtml/uwsgi_proxy.conf:/etc/nginx/viahtml/uwsgi_proxy.conf:ro
      - ./conf/nginx/viahtml_dev/app_upstream.conf:/etc/nginx/viahtml/app_upstream.conf:ro
      - ./conf/nginx/dev_host_bridge.sh:/etc/nginx/dev_host_bridge.sh:ro
      - ./static:/var/lib/hypothesis/static:ro
    command: /bin/sh -c "/etc/nginx/dev_host_bridge.sh && exec nginx"


