name: Deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  create-image:
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  qa-viahtml:
    needs: create-image
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: ${{ github.event.repository.name }}
      Environment: qa
      Region: us-west-1
      Operation: deploy
      Version: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  qa-lms-viahtml:
    needs: create-image
    name: lms-viahtml
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: lms-viahtml
      Environment: qa
      Region: us-west-1
      Operation: deploy
      Version: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod-viahtml:
    needs: [create-image, qa-viahtml]
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: ${{ github.event.repository.name }}
      Environment: prod
      Region: us-west-1
      Operation: deploy
      Version: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod-lms-viahtml:
    needs: [create-image, qa-lms-viahtml]
    name: lms-viahtml
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: lms-viahtml
      Environment: prod
      Region: us-west-1
      Operation: deploy
      Version: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit
