name: Deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  create-image:
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  qa-viahtml:
    needs: create-image
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      github_environment_url: https://qa-via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  qa-lms-viahtml:
    needs: create-image
    name: lms-viahtml
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA (Edu)
      github_environment_url: https://qa-lms-via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: lms-viahtml
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod-viahtml:
    needs: qa-viahtml
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod-lms-viahtml:
    needs: qa-lms-viahtml
    name: lms-viahtml
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Edu)
      github_environment_url: https://lms-via.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: lms-viahtml
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit
