name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.cookiecutter/*'
      - '.github/*'
      - 'docs/*'
      - 'requirements/*'
      - '!requirements/requirements.txt'
      - 'tests/*'
      - '**/.gitignore'
      - '*.md'
      - 'tox.ini'
jobs:
  docker_hub:
    name: Docker Hub
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit
  qa:
    name: QA
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      github_environment_url: https://qa-via.hypothes.is/https://en.wikipedia.org/wiki/Diplodocus
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  qa_edu:
    name: QA (Edu)
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/877
      aws_region: us-west-1
      elasticbeanstalk_application: lms-viahtml
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  staging:
    name: Staging
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Staging
      github_environment_url: https://via.staging.hypothes.is/https://en.wikipedia.org/wiki/Diplodocus
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: staging
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  staging_edu:
    name: Staging (Edu)
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Staging (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/877
      aws_region: us-west-1
      elasticbeanstalk_application: edu-viahtml
      elasticbeanstalk_environment: staging
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  production:
    name: Production
    needs: [docker_hub, qa]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://via.hypothes.is/https://en.wikipedia.org/wiki/Diplodocus
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  production_edu:
    name: Production (Edu)
    needs: [docker_hub, qa_edu]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/881
      aws_region: us-west-1
      elasticbeanstalk_application: lms-viahtml
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
