name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      qa:
        type: boolean
        description: Redeploy QA
      qa_edu:
        type: boolean
        description: Redeploy QA (Edu)
      staging:
        type: boolean
        description: Redeploy Staging
      staging_edu:
        type: boolean
        description: Redeploy Staging (Edu)
      production:
        type: boolean
        description: Redeploy Production
      production_edu:
        type: boolean
        description: Redeploy Production (Edu)
jobs:
  qa:
    name: QA
    if: inputs.qa
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA
      github_environment_url: https://qa-via.hypothes.is/https://en.wikipedia.org/wiki/Diplodocus
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: qa
    secrets: inherit
  qa_edu:
    name: QA (Edu)
    if: inputs.qa_edu
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/877
      aws_region: us-west-1
      elasticbeanstalk_application: lms-viahtml
      elasticbeanstalk_environment: qa
    secrets: inherit
  staging:
    name: Staging
    if: inputs.staging
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Staging
      github_environment_url: https://via.staging.hypothes.is/https://en.wikipedia.org/wiki/Diplodocus
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: staging
    secrets: inherit
  staging_edu:
    name: Staging (Edu)
    if: inputs.staging_edu
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Staging (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/877
      aws_region: us-west-1
      elasticbeanstalk_application: edu-viahtml
      elasticbeanstalk_environment: staging
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://via.hypothes.is/https://en.wikipedia.org/wiki/Diplodocus
      aws_region: us-west-1
      elasticbeanstalk_application: viahtml
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_edu:
    name: Production (Edu)
    if: inputs.production_edu
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Edu)
      github_environment_url: https://hypothesis.instructure.com/courses/125/assignments/881
      aws_region: us-west-1
      elasticbeanstalk_application: lms-viahtml
      elasticbeanstalk_environment: prod
    secrets: inherit
